rawset(_G, "VR_waves", {
	-- POSSIBLE ENEMIES PER CHALLENGE:
	
	-- CHALLENGE 1:
	[1] = {

			{	"maya_vr",
				"maya_vr",
			},

			{	"hand_vr",
				"maya_vr",
			},

			{	"table_vr",
				"maya_vr",
			},
	},

	-- CHALLENGE 1 BOSS
	[3] = {
			
			{"beetle_vr"},

	},
	
	-- CHALLENGE 2:
	[4] = {

		{	"balance_1_postboss",
			"table_1_postboss",
			"balance_1_postboss"
		},

		{	"hablerie_1_postboss",
			"beetle_1",
			"maya_1_postboss"
		},

		{	"table_1_postboss",
			"mage_1",
			"table_1_postboss"
		},

		{	"relic_1",
			"maya_1_postboss",
			"cupid_1",
		},

		{	"hand_1_postboss",
			"relic_1",
			"hand_1_postboss",
		},

		{	"maya_1_postboss",
			"cupid_1",
			"maya_1_postboss",
			"maya_1_postboss"
		},

		{	"maya_1_postboss",
			"balance_1_postboss",
			"maya_1_postboss",
			"balance_1_postboss"
		},

		{	"table_1_postboss",
			"table_1_postboss",
			"table_1_postboss"
		},
		
		{
			"hablerie_1_postboss",
			"cupid_1",
			"hablerie_1_postboss",
		},
		
		{
			"table_1_postboss",
			"cupid_1",
			"cupid_1",
			"hablerie_1_postboss",
		},

	},
	
	-- CHALLENGE 2 BOSS
	[6] = {
			
			{"knight_vr"},

	},	

	-- CHALLENGE 3
	[7] = {

		{
			"book_1",
			"tiara_1_postboss",
			"beast_1_postboss",
			"basalt_1",
		},

		{	"wheel_1"},
		{	"wheel_1"},	-- make wave a bit more common		

		{
			"maya_2_postboss",
			"beast_1_postboss",
			"maya_2_postboss",
			"beast_1_postboss",
		},

		{
			"sword_1_postboss",
			"twins_1",
			"twins_1",
			"pesce_1_postboss",
		},

		{
			"tiara_1_postboss",
			"tiara_1_postboss",
			"basalt_1",
			"tiara_1_postboss",
		},

		{
			"balance_2",
			"balance_3",
			"fuzz_1_postboss",
		},

		{
			"balance_3",
			"maya_2_postboss",
			"maya_2_postboss",
		},

		{
			"twins_1",
			"book_1",
			"twins_1",
			"basalt_1",
		},
		
		{
			"pesce_1_postboss",
			"maya_2_postboss",
			"pesce_1_postboss",
		},
		
		{
			"fuzz_1_postboss",
			"basalt_1",
			"basalt_1",
			"fuzz_1_postboss",
		},
		
		{
			"balance_3",
			"pesce_1_postboss",
			"balance_3",
		},
		
		{
			"pesce_1_postboss",
			"twins_1",
			"twins_1",
			"fuzz_1_postboss",
		},
		
		{
			"basalt_1",
			"maya_2_postboss",
			"fuzz_1_postboss",
			"sword_1_postboss",
		},		

		{
			"sword_1_postboss",
			"maya_2_postboss",
			"pesce_1_postboss",
			"sword_1_postboss",
		},			
		
	},
	
	-- CHALLENGE 3 BOSSES
	[9] = {
				{"gigas_vr"},
				{"magus_vr"},
		},

	-- CHALLENGE 4
	[10] = {

		{
			"book_1",
			"tiara_1_postboss",
			"beast_1_postboss",
			"basalt_1",
		},

		{	"wheel_1"},
		{	"wheel_1"},	-- make wave a bit more common		

		{
			"maya_2_postboss",
			"beast_1_postboss",
			"maya_2_postboss",
			"beast_1_postboss",
		},

		{
			"sword_1_postboss",
			"twins_1",
			"twins_1",
			"pesce_1_postboss",
		},

		{
			"tiara_1_postboss",
			"tiara_1_postboss",
			"basalt_1",
			"tiara_1_postboss",
		},

		{
			"balance_2",
			"balance_3",
			"fuzz_1_postboss",
		},

		{
			"balance_3",
			"maya_2_postboss",
			"maya_2_postboss",
		},

		{
			"twins_1",
			"book_1",
			"twins_1",
			"basalt_1",
		},
		
		{
			"pesce_1_postboss",
			"maya_2_postboss",
			"pesce_1_postboss",
		},
		
		{
			"fuzz_1_postboss",
			"basalt_1",
			"basalt_1",
			"fuzz_1_postboss",
		},
		
		{
			"balance_3",
			"pesce_1_postboss",
			"balance_3",
		},
		
		{
			"pesce_1_postboss",
			"twins_1",
			"twins_1",
			"fuzz_1_postboss",
		},
		
		{
			"basalt_1",
			"maya_2_postboss",
			"fuzz_1_postboss",
			"sword_1_postboss",
		},		

		{
			"sword_1_postboss",
			"maya_2_postboss",
			"pesce_1_postboss",
			"sword_1_postboss",
		},			
		
	},
	
	-- CHALLENGE 4 BOSS
	[12] = {
		{"giant_vr"},
	},

	-- CHALLENGE 5:
	[13] = {

		{
			"maya_tziah",
			"maya_tziah",
			"maya_tziah",
		},

		{
			"relic_tziah",
			"giant_tziah",
			"relic_tziah",
		},

		{
			"relic_tziah",
			"relic_tziah",
		},

		{
			"drive_tziah",
			"gigas_tziah",
			"gigas_tziah",
		},

		{
			"twins_tziah",
			"beetle_tziah",
			"twins_tziah",
		},

		{
			"minotaur_tziah",
			"maya_tziah",
		},

		{
			"beast_tziah",
			"giant_tziah",
			"beast_tziah",
		},

		{
			"cyclops_tziah",
			"turret_tziah",
			"turret_tziah",
		},

		{
			"gigas_tziah",
			"maya_tziah",
			"relic_tziah",
		},

		{
			"twins_tziah",
			"beast_tziah",
		},
	},

	
	-- CHALLENGE 5 BOSS
	[15] = {
		{"angel_vr"}
	},
	
	-- CHALLENGE 6
	[16] = {

		{
			"maya_tziah",
			"machine_tziah",
			"maya_tziah",
		},

		{
			"relic_tziah",
			"giant_tziah",
			"panzer_tziah",
		},

		{
			"relic_tziah",
			"relic_tziah",
			"panzer_tziah",
		},

		{
			"idol_tziah",
			"mother_tziah",
			"pesce_tziah",
			"idol_tziah",
		},

		{
			"drive_tziah",
			"gigas_tziah",
			"gigas_tziah",
			"idol_tziah",
		},

		{
			"giant_tziah",
			"giant_tziah",
			"snake_tziah",
			"pesce_tziah",
		},

		{
			"twins_tziah",
			"beetle_tziah",
			"twins_tziah",
		},

		{
			"maya_tziah",
			"snake_tziah",
			"mother_tziah",
		},

		{
			"magus_tziah",
			"twins_tziah",
			"twins_tziah",
			"magus_tziah",
		},

		{
			"snake_tziah",
			"giant_tziah",
			"snake_tziah",
			"giant_tziah",
		},

		{
			"cyclops_tziah",
			"turret_tziah",
			"turret_tziah",
			"maya_tziah",
		},

		{
			"idol_tziah",
			"idol_tziah",
			"turret_tziah",
		},

		{
			"gigas_tziah",
			"maya_tziah",
			"relic_tziah",
			"maya_tziah",
		},

		{
			"twins_tziah",
			"beast_tziah",
			"pesce_tziah",
		},

		{
			"mother_tziah",
			"machine_tziah",
			"drive_tziah",
		},
	},	
	
	-- CHALLENGE 6 BOSS:
	[18] = {
		{"giant_vr_2"},
	},

	[19] = {
		{	"maya_harabah",
			"maya_harabah",
			"maya_harabah",
		},

		{	"twins_harabah",
			"twins_harabah",
			"fuzz_harabah",
		},

		{	"snake_harabah",
			"knight_harabah",
			"fuzz_harabah",
		},

		{	"idol_harabah",
			"maya_harabah",
			"twins_harabah",
		},

		{	"tower_harabah",
			"drive_harabah",
		},

		{	"knight_harabah",
			"knight_harabah",
			"idol_harabah",
		},

		{	"idol_harabah",
			"idol_harabah",
			"maya_harabah",
		},

		{	"drive_harabah",
			"snake_harabah",
			"snake_harabah",
		},	
	},
	
	-- CHALLENGE 7 BOSS
	[21] = {
		{"sword_vr_2"},
	},
	
	-- CHALLENGE 8
	[22] = {
		{	"maya_harabah",
			"machine_harabah",
			"maya_harabah",
		},

		{	"knight_harabah",
			"knight_harabah",
			"knight_harabah",
		},

		{	"twins_harabah",
			"twins_harabah",
			"table_harabah",
		},

		{	"snake_harabah",
			"knight_harabah",
			"snake_harabah",
			"eagle_harabah",
		},

		{	"idol_harabah",
			"okina_harabah",
			"maya_harabah",
			"twins_harabah",
		},

		{	"cyclops_harabah",
			"maya_harabah"
		},

		{	"cyclops_harabah",
			"twins_harabah",
		},

		{	"tower_harabah",
			"drive_harabah",
			"table_harabah",
		},

		{	"knight_harabah",
			"idol_harabah",
			"okina_harabah",
		},

		{	"dice_harabah",
			"dice_harabah",
			"table_harabah",
		},

		{	"idol_harabah",
			"okina_harabah",
			"dice_harabah",
		},

		{	"drive_harabah",
			"snake_harabah",
			"table_harabah",

		},	
	},
	-- CHALLENGE 8 BOSS
	
	[24] = {
		{"eagle_vr_2"},
	},
	
	-- CHALLENGE 9
	[25] =	{
		{
			"sand_adamah",
			"maya_adamah",
		},

		{
			"twins_adamah",
			"turret_adamah",
			"twins_adamah",
		},

		{
			"balance_adamah",
			"beetle_adamah",
		},

		{
			"dice_adamah",
			"beetle_adamah",
			"dice_adamah",
		},

		{
			"turret_adamah",
			"castle_adamah",
		},

		{
			"gene_adamah",
			"castle_adamah",
		},

		{
			"hand_adamah",
			"table_adamah",
			"hand_adamah",
		},

		{
			"giant_adamah",
			"castle_adamah",
			"giant_adamah",
		},

		{
			"phantom_adamah",
			"dice_adamah",
			"phantom_adamah",
		},

		{
			"gene_adamah",
			"phantom_adamah",
			"gene_adamah",
		},

		{
			"sand_adamah",
			"beetle_adamah",
			"sand_adamah",
		},

		{
			"maya_adamah",
			"hand_adamah",
			"maya_adamah",
		},

		{
			"balance_adamah",
			"gene_adamah",
			"balance_adamah",
		},
		
		{
			"balance_adamah",
			"snake_adamah",
			"balance_adamah",
		},

		{
			"sand_adamah",
			"gene_adamah",
			"gigas_adamah",
		},

		{
			"idol_adamah",
			"pesce_adamah",
			"idol_adamah",
		},

		{
			"idol_adamah",
			"hand_adamah",
			"maya_adamah",
			"idol_adamah",
		},

		{
			"pesce_adamah",
			"pesce_adamah",
		},

		{
			"snake_adamah",
			"idol_adamah",
			"snake_adamah",
		},

		{
			"dice_adamah",
			"gene_adamah",
			"idol_adamah",
		},

		{
			"snake_adamah",
			"knight_adamah",
			"snake_adamah",
		},

		{
			"drive_adamah",
			"giant_adamah",
			"drive_adamah",
		},
	},
	
	-- CHALLENGE 9 BOSS
	[27] = {
		{"knight_vr_2"},
	},
	
	[28] = {
		{
			"sand_adamah",
			"maya_adamah",
			"sand_adamah",
		},

		{
			"twins_adamah",
			"turret_adamah",
			"turret_adamah",
			"twins_adamah",
		},

		{
			"balance_adamah",
			"beetle_adamah",
			"balance_adamah",
		},

		{
			"dice_adamah",
			"beetle_adamah",
			"dice_adamah",
		},

		{
			"turret_adamah",
			"turret_adamah",
			"turret_adamah",
			"castle_adamah",
		},

		{
			"gene_adamah",
			"castle_adamah",
			"castle_adamah",
		},

		{
			"hand_adamah",
			"table_adamah",
			"table_adamah",
			"hand_adamah",
		},

		{
			"giant_adamah",
			"castle_adamah",
			"giant_adamah",
		},

		{
			"phantom_adamah",
			"dice_adamah",
			"phantom_adamah",
		},

		{
			"gene_adamah",
			"phantom_adamah",
			"phantom_adamah",
			"gene_adamah",
		},

		{
			"sand_adamah",
			"beetle_adamah",
			"beetle_adamah",
			"sand_adamah",
		},

		{
			"maya_adamah",
			"hand_adamah",
			"hand_adamah",
			"maya_adamah",
		},

		{
			"balance_adamah",
			"gene_adamah",
			"balance_adamah",
		},
		
		{
			"balance_adamah",
			"snake_adamah",
			"balance_adamah",
		},

		{
			"gigas_adamah",
			"sand_adamah",
			"gene_adamah",
			"gigas_adamah",
		},

		{
			"idol_adamah",
			"pesce_adamah",
			"idol_adamah",
		},

		{
			"idol_adamah",
			"hand_adamah",
			"maya_adamah",
			"idol_adamah",
		},

		{
			"pesce_adamah",
			"pesce_adamah",
		},

		{
			"snake_adamah",
			"idol_adamah",
			"snake_adamah",
		},

		{
			"dice_adamah",
			"gene_adamah",
			"idol_adamah",
		},

		{
			"snake_adamah",
			"knight_adamah",
			"snake_adamah",
		},

		{
			"drive_adamah",
			"giant_adamah",
			"drive_adamah",
		},
	},
	
	-- CHALLENGE 10 BOSS:
	[30] = {
		{"reaper_vr"},
	}
})