-- tartarus enemy waves

-- other dungeon waves are defined elsewhere

local monad_waves = {
	{
		"maya_monad",
		"mage_monad",
		"maya_monad",
	},
	
	{
		"maya_monad",
		"hablerie_monad",
		"maya_monad",
	},	
	
	{
		"sand_monad",
		"maya_monad",
		"sand_monad",
	},	

	{
		"eagle_monad",
		"musha_monad",
		"musha_monad",
	},
	
	{
		"maya_monad",
		"tower_monad",
		"maya_monad",
		"maya_monad",
	},	
	
	{
		"musha_monad",
		"giant_monad",
		"mage_monad",
		"mage_monad",
	},		

	{
		"knight_monad",
		"hablerie_monad",
		"knight_monad",
		"maya_monad",
	},
	
	{
		"sand_monad",
		"turret_monad",
		"sand_monad",
	},
	
	{
		"turret_monad",
		"giant_monad",
		"turret_monad",
	},
	
	{
		"turret_monad",
		"tower_monad",
		"turret_monad",
	},	

}

local monad_waves_strong = {

	{
		"maya_monad",
		"basalt_monad",
		"maya_monad",
	},

	{
		"maya_monad",
		"machine_monad",
		"maya_monad",
	},

	{
		"maya_monad",
		"okina_monad",
		"maya_monad",
		"turret_monad",
	},
	
	{
		"sand_monad",
		"okina_monad",
		"sand_monad",
		"gigas_monad",
	},	

	{
		"eagle_monad",
		"musha_monad",
		"musha_monad",
		"turret_monad",
	},
	
	{
		"maya_monad",
		"okina_monad",
		"maya_monad",
		"maya_monad",
		"gigas_monad",
	},	
	
	{
		"musha_monad",
		"giant_monad",
		"giant_monad",
		"mage_monad",
		"mage_monad",
	},		

	{
		"knight_monad",
		"giant_monad",
		"knight_monad",
		"maya_monad",
	},
	
	{
		"sand_monad",
		"turret_monad",
		"sand_monad",
		"gigas_monad",
	},
	
	{
		"turret_monad",
		"giant_monad",
		"turret_monad",
		"giant_monad",
	},
	
	{
		"turret_monad",
		"tower_monad",
		"turret_monad",
		"gigas_monad",
	},	

}

local adamah_waves = {
		{
			"sand_adamah",
			"maya_adamah",
			"sand_adamah",
		},

		{
			"twins_adamah",
			"turret_adamah",
			"turret_adamah",
			"twins_adamah",
		},

		{
			"balance_adamah",
			"beetle_adamah",
			"balance_adamah",
		},

		{
			"dice_adamah",
			"beetle_adamah",
			"dice_adamah",
		},

		{
			"turret_adamah",
			"turret_adamah",
			"turret_adamah",
			"castle_adamah",
		},

		{
			"gene_adamah",
			"castle_adamah",
			"castle_adamah",
		},

		{
			"hand_adamah",
			"table_adamah",
			"table_adamah",
			"hand_adamah",
		},

		{
			"giant_adamah",
			"castle_adamah",
			"giant_adamah",
		},

		{
			"phantom_adamah",
			"dice_adamah",
			"phantom_adamah",
		},

		{
			"gene_adamah",
			"phantom_adamah",
			"phantom_adamah",
			"gene_adamah",
		},

		{
			"sand_adamah",
			"beetle_adamah",
			"beetle_adamah",
			"sand_adamah",
		},

		{
			"maya_adamah",
			"hand_adamah",
			"hand_adamah",
			"maya_adamah",
		},

		{
			"balance_adamah",
			"gene_adamah",
			"balance_adamah",
		},
		
		{
			"balance_adamah",
			"snake_adamah",
			"balance_adamah",
		},

		{
			"gigas_adamah",
			"sand_adamah",
			"gene_adamah",
			"gigas_adamah",
		},

		{
			"idol_adamah",
			"pesce_adamah",
			"idol_adamah",
		},

		{
			"idol_adamah",
			"hand_adamah",
			"maya_adamah",
			"idol_adamah",
		},

		{
			"pesce_adamah",
			"pesce_adamah",
		},

		{
			"snake_adamah",
			"idol_adamah",
			"snake_adamah",
		},

		{
			"dice_adamah",
			"gene_adamah",
			"idol_adamah",
		},

		{
			"snake_adamah",
			"knight_adamah",
			"snake_adamah",
		},

		{
			"drive_adamah",
			"giant_adamah",
			"drive_adamah",
		},
}

local adamah_waves_strong = {
		{
			"idol_adamah",
			"nyogo_adamah",
			"idol_adamah",
		},

		{
			"giant_adamah",
			"turret_adamah",
			"turret_adamah",
			"twins_adamah",
		},

		{
			"balance_adamah",
			"giant_adamah",
			"balance_adamah",
		},

		{
			"gene_adamah",
			"knight_adamah",
			"gene_adamah",
		},

		{
			"castle_adamah",
			"turret_adamah",
			"turret_adamah",
			"castle_adamah",
		},

		{
			"minotaur_adamah",
			"dice_adamah",
			"minotaur_adamah",
		},

		{
			"dice_adamah",
			"dice_adamah",
			"nyogo_adamah",
			"dice_adamah",
			"dice_adamah",
		},

		{
			"giant_adamah",
			"giant_adamah",
			"giant_adamah",
		},

		{
			"snake_adamah",
			"phantom_adamah",
			"panzer_adamah",
			"phantom_adamah",
		},

		{
			"dice_adamah",
			"nyogo_adamah",
			"phantom_adamah",
			"dice_adamah",
		},

		{
			"sand_adamah",
			"beetle_adamah",
			"drive_adamah",
			"sand_adamah",
		},

		{
			"gene_adamah",
			"hand_adamah",
			"hand_adamah",
			"gene_adamah",
		},

		{
			"idol_adamah",
			"hand_adamah",
			"hand_adamah",
			"idol_adamah",
		},

		{
			"balance_adamah",
			"panzer_adamah",
			"balance_adamah",
		},
		
		{
			"pesce_adamah",
			"nyogo_adamah",
			"pesce_adamah",
		},

		{
			"gigas_adamah",
			"sand_adamah",
			"maya_adamah",
			"gigas_adamah",
		},

		{
			"idol_adamah",
			"idol_adamah",
			"minotaur_adamah",
			"idol_adamah",
		},

		{
			"idol_adamah",
			"hand_adamah",
			"maya_adamah",
			"idol_adamah",
		},

		{
			"minotaur_adamah",
			"minotaur_adamah",
		},

		{
			"snake_adamah",
			"panzer_adamah",
			"snake_adamah",
		},

		{
			"idol_adamah",
			"minotaur_adamah",
			"idol_adamah",
		},

		{
			"snake_adamah",
			"knight_adamah",
			"snake_adamah",
		},

		{
			"drive_adamah",
			"giant_adamah",
			"nyogo_adamah",
		},

		{
			"idol_adamah",
			"idol_adamah",
			"idol_adamah",
			"dice_adamah",
		},
}

rawset(_G, "DNG_waves", {

	/*[blockfloor[BLOCK_ADAMAH]] = {
		{	"humptihiko"
		}
	},*/

	-- ENEMIES: MONAD DEPTHS
	[blockfloor[BLOCK_MONAD]] = monad_waves,	-- B1F
	[blockfloor[BLOCK_MONAD]+5] = {
									{"drive_boss_monad"}
								},
								
	[blockfloor[BLOCK_MONAD]+6] = monad_waves_strong,							
	[blockfloor[BLOCK_MONAD]+9] = {
									{"table_boss_monad"}
								},

	[blockfloor[BLOCK_MONAD]+10] = monad_waves_strong,							
	[blockfloor[BLOCK_MONAD]+14] = {
									{"maya_boss_monad"}
								},
	[blockfloor[BLOCK_MONAD]+15] = {
									{"reaper_alt"}
								},

	-- ENEMIES: ADAMAH BLOCK

	/*[blockfloor[BLOCK_ADAMAH]] = {12},		-- 90F: Adamah random floor
	[blockfloor[BLOCK_ADAMAH]+4] = {13},	-- 94F: Adamah, boss 1
	[blockfloor[BLOCK_ADAMAH]+5] = {12},	-- 95F: Adamah random floor
	[blockfloor[BLOCK_ADAMAH]+8] = {13},	-- 98F: Adamah, boss 2
	[blockfloor[BLOCK_ADAMAH]+9] = {12},	-- 99F: Adamah random floor
	[blockfloor[BLOCK_ADAMAH]+14] = {13},	-- 103F: Adamah, boss 3
	[blockfloor[BLOCK_ADAMAH]+15] = {12},	-- 104F: Adamah random floor
	[blockfloor[BLOCK_ADAMAH]+20] = {13},	-- 109F: Adamah, boss 4
	[blockfloor[BLOCK_ADAMAH]+21] = {12},	-- 110F: Adamah random floor
	[blockfloor[BLOCK_ADAMAH]+22] = {13},	-- 111F: Adamah, boss 5	(final)*/

	[blockfloor[BLOCK_ADAMAH]] = adamah_waves, 	-- 90F:
	[blockfloor[BLOCK_ADAMAH]+4] = {			-- 94F:
										{	"eagle_boss1_adamah",
											"eagle_boss1_adamah",
											"eagle_boss1_adamah",
										}
									},
	[blockfloor[BLOCK_ADAMAH]+5] = adamah_waves, 	-- 95F:
	[blockfloor[BLOCK_ADAMAH]+8] = {				-- 98F:
										{	"hand_boss1_adamah",
										}
									},

	[blockfloor[BLOCK_ADAMAH]+9] = adamah_waves_strong, 	-- 99F:
	[blockfloor[BLOCK_ADAMAH]+13] = {				-- 103F:
										{	"sword_boss1_adamah",
											"sword_boss1_adamah",
											"sword_boss1_adamah",
										}
									},

	[blockfloor[BLOCK_ADAMAH]+14] = adamah_waves_strong, 	-- 104F:
	[blockfloor[BLOCK_ADAMAH]+19] = {				-- 109F:
										{	"knight_boss1_adamah",
											"knight_boss1_adamah",
											"knight_boss1_adamah",
										}
									},

	[blockfloor[BLOCK_ADAMAH]+20] = adamah_waves_strong, 	-- 110F:
	[blockfloor[BLOCK_ADAMAH]+21] = {				-- 111F:
										{	"balance_boss1_adamah",
										}
									},


	-- ENEMIES: HARABAH BLOCK

/*
	[blockfloor[BLOCK_HARABAH]] = {10},		-- 65F: random floor, harabah block
	[blockfloor[BLOCK_HARABAH]+5] = {11},	-- 70F: Harabah boss 1
	[blockfloor[BLOCK_HARABAH]+6] = {10},	-- 71F: Harabah random floor
	[blockfloor[BLOCK_HARABAH]+10] = {11},	-- 75F: Harabah boss 2
	[blockfloor[BLOCK_HARABAH]+11] = {10},	-- 76F: Harabah random floor
	[blockfloor[BLOCK_HARABAH]+14] = {11},	-- 79F: Harabah boss 3
	[blockfloor[BLOCK_HARABAH]+15] = {10},	-- 80F: Harabah random floor
	[blockfloor[BLOCK_HARABAH]+18] = {11},	-- 83F: Harabah boss 4
	[blockfloor[BLOCK_HARABAH]+19] = {10},	-- 84F: Harabah random floor
	[blockfloor[BLOCK_HARABAH]+23] = {11},	-- 88F: Harabah boss 5 	(final)
*/

	[blockfloor[BLOCK_HARABAH]+23] = {
		{	"dice_boss1_harabah",
		},
	},

	[blockfloor[BLOCK_HARABAH]+19] = {

		{	"maya_harabah",
			"maya_harabah",
			"machine_harabah",
			"maya_harabah",
			"maya_harabah",
		},

		{	"knight_harabah",
			"knight_harabah",
			"knight_harabah",
			"dancer_harabah",
		},

		{	"twins_harabah",
			"twins_harabah",
			"table_harabah",
			"maya_harabah",
		},

		{	"snake_harabah",
			"knight_harabah",
			"snake_harabah",
			"eagle_harabah",
		},

		{	"idol_harabah",
			"maya_harabah",
			"maya_harabah",
			"twins_harabah",
		},

		{	"cyclops_harabah",
			"fuzz_harabah"
		},

		{	"cyclops_harabah",
			"dancer_harabah",
		},

		{	"tower_harabah",
			"drive_harabah",
			"tower_harabah",
			"table_harabah",
		},

		{	"knight_harabah",
			"knight_harabah",
			"idol_harabah",
			"okina_harabah",
		},

		{	"dice_harabah",
			"dice_harabah",
			"eagle_harabah",
			"table_harabah",
		},

		{	"idol_harabah",
			"idol_harabah",
			"okina_harabah",
			"dancer_harabah",
		},

		{	"drive_harabah",
			"snake_harabah",
			"snake_harabah",
			"table_harabah",

		},
	},

	[blockfloor[BLOCK_HARABAH]+18] = {
		{	"dancer_boss1_harabah",
			"dancer_boss1_harabah",
			"dancer_boss1_harabah",
		},
	},

	[blockfloor[BLOCK_HARABAH]+15] = {

		{	"maya_harabah",
			"maya_harabah",
			"machine_harabah",
			"maya_harabah",
			"maya_harabah",
		},

		{	"knight_harabah",
			"knight_harabah",
			"knight_harabah",
		},

		{	"twins_harabah",
			"twins_harabah",
			"table_harabah",
			"okina_harabah",
		},

		{	"snake_harabah",
			"knight_harabah",
			"snake_harabah",
			"eagle_harabah",
		},

		{	"idol_harabah",
			"okina_harabah",
			"maya_harabah",
			"twins_harabah",
		},

		{	"cyclops_harabah",
			"maya_harabah"
		},

		{	"cyclops_harabah",
			"twins_harabah",
		},

		{	"tower_harabah",
			"drive_harabah",
			"tower_harabah",
			"table_harabah",
		},

		{	"knight_harabah",
			"knight_harabah",
			"idol_harabah",
			"okina_harabah",
		},

		{	"dice_harabah",
			"dice_harabah",
			"eagle_harabah",
			"table_harabah",
		},

		{	"idol_harabah",
			"idol_harabah",
			"okina_harabah",
			"dice_harabah",
		},

		{	"drive_harabah",
			"snake_harabah",
			"snake_harabah",
			"table_harabah",

		},
	},

	[blockfloor[BLOCK_HARABAH]+14] = {
		{	"giant_boss1_harabah",
			"giant_boss1_harabah",
			"giant_boss1_harabah",
		},
	},

	[blockfloor[BLOCK_HARABAH]+11] = {

		{	"maya_harabah",
			"maya_harabah",
			"maya_harabah",
			"maya_harabah",
			"maya_harabah",
		},

		{	"knight_harabah",
			"knight_harabah",
			"knight_harabah",
		},

		{	"twins_harabah",
			"twins_harabah",
			"table_harabah",
			"fuzz_harabah",
		},

		{	"snake_harabah",
			"knight_harabah",
			"snake_harabah",
			"eagle_harabah",
		},

		{	"idol_harabah",
			"okina_harabah",
			"okina_harabah",
			"twins_harabah",
		},

		{	"tower_harabah",
			"okina_harabah",
			"okina_harabah",
			"table_harabah",
		},

		{	"knight_harabah",
			"knight_harabah",
			"idol_harabah",
			"fuzz_harabah",
		},

		{	"dice_harabah",
			"dice_harabah",
			"eagle_harabah",
			"table_harabah",
		},

		{	"table_harabah",
			"table_harabah",
			"maya_harabah",
			"dice_harabah",
		},

		{	"drive_harabah",
			"snake_harabah",
			"snake_harabah",
			"table_harabah",

		},
		
		{
			"fuzz_harabah",
			"machine_harabah",
			"fuzz_harabah",
		},
	},

	[blockfloor[BLOCK_HARABAH]+10] = {
		{	"phantom_boss1_harabah"
		},
	},

	[blockfloor[BLOCK_HARABAH]+6] = {

		{	"maya_harabah",
			"maya_harabah",
			"maya_harabah",
			"maya_harabah",
			"maya_harabah",
		},

		{	"twins_harabah",
			"twins_harabah",
			"table_harabah",
			"maya_harabah",
		},

		{	"snake_harabah",
			"knight_harabah",
			"snake_harabah",
			"eagle_harabah",
		},

		{	"idol_harabah",
			"maya_harabah",
			"maya_harabah",
			"twins_harabah",
		},

		{	"tower_harabah",
			"drive_harabah",
			"tower_harabah",
			"table_harabah",
		},

		{	"knight_harabah",
			"knight_harabah",
			"idol_harabah",
			"fuzz_harabah",
		},

		{	"dice_harabah",
			"dice_harabah",
			"eagle_harabah",
			"fuzz_harabah",
		},

		{	"idol_harabah",
			"idol_harabah",
			"maya_harabah",
			"dice_harabah",
		},

		{	"drive_harabah",
			"snake_harabah",
			"snake_harabah",
			"table_harabah",

		},
		
		{
			"machine_harabah",
		},
	},

	[blockfloor[BLOCK_HARABAH]+5] = {
		{	"sword_boss1_harabah",
			"sword_boss1_harabah",
			"sword_boss1_harabah",
		},
	},

	[blockfloor[BLOCK_HARABAH]] = {

		{	"maya_harabah",
			"maya_harabah",
			"maya_harabah",
			"maya_harabah",
		},

		{	"twins_harabah",
			"twins_harabah",
			"fuzz_harabah",
		},

		{	"snake_harabah",
			"knight_harabah",
			"fuzz_harabah",
		},

		{	"idol_harabah",
			"maya_harabah",
			"maya_harabah",
			"twins_harabah",
		},

		{	"tower_harabah",
			"drive_harabah",
			"tower_harabah",
		},

		{	"knight_harabah",
			"knight_harabah",
			"idol_harabah",
		},

		{	"idol_harabah",
			"idol_harabah",
			"maya_harabah",
		},

		{	"drive_harabah",
			"snake_harabah",
			"snake_harabah",
		},
	},

	-- ENEMIES: TZIAH BLOCK

	-- 63F: Tziah boss 4 (final): Sleeping Table
	[blockfloor[BLOCK_TZIAH] + 18] = {
		{	"table_boss1_tziah" }
	},

	-- 61F: Tziah random waves 4
	[blockfloor[BLOCK_TZIAH] +16] = {

		{
			"maya_tziah",
			"machine_tziah",
			"maya_tziah",
		},

		{
			"relic_tziah",
			"giant_tziah",
			"panzer_tziah",
		},

		{
			"relic_tziah",
			"minotaur_tziah",
			"relic_tziah",
			"panzer_tziah",
		},

		{
			"idol_tziah",
			"mother_tziah",
			"pesce_tziah",
			"idol_tziah",
		},

		{
			"drive_tziah",
			"gigas_tziah",
			"gigas_tziah",
			"idol_tziah",
		},

		{
			"giant_tziah",
			"giant_tziah",
			"snake_tziah",
			"pesce_tziah",
		},

		{
			"twins_tziah",
			"beetle_tziah",
			"twins_tziah",
		},

		{
			"maya_tziah",
			"minotaur_tziah",
			"snake_tziah",
			"mother_tziah",
		},

		{
			"magus_tziah",
			"twins_tziah",
			"twins_tziah",
			"magus_tziah",
		},

		{
			"snake_tziah",
			"giant_tziah",
			"snake_tziah",
			"giant_tziah",
		},

		{
			"cyclops_tziah",
			"turret_tziah",
			"turret_tziah",
			"maya_tziah",
		},

		{
			"idol_tziah",
			"idol_tziah",
			"turret_tziah",
		},

		{
			"gigas_tziah",
			"maya_tziah",
			"relic_tziah",
			"maya_tziah",
		},

		{
			"twins_tziah",
			"beast_tziah",
			"pesce_tziah",
		},

		{
			"mother_tziah",
			"machine_tziah",
			"drive_tziah",
		},
	},

	-- 60F: Tziah boss 3: 3 Oath Giants
	[blockfloor[BLOCK_TZIAH] +15] = {
		{
			"giant_boss1_tziah",
			"giant_boss1_tziah",
			"giant_boss1_tziah",
		},
	},

	-- 56F: Tziah random waves 3
	[blockfloor[BLOCK_TZIAH] +11] = {

		{
			"maya_tziah",
			"idol_tziah",
			"maya_tziah",
		},

		{
			"relic_tziah",
			"giant_tziah",
			"mother_tziah",
		},

		{
			"relic_tziah",
			"minotaur_tziah",
			"relic_tziah",
		},

		{
			"drive_tziah",
			"gigas_tziah",
			"gigas_tziah",
			"idol_tziah",
		},

		{
			"giant_tziah",
			"giant_tziah",
			"snake_tziah",
		},

		{
			"twins_tziah",
			"beetle_tziah",
			"twins_tziah",
		},

		{
			"pesce_tziah",
			"minotaur_tziah",
			"snake_tziah",
		},

		{
			"magus_tziah",
			"twins_tziah",
			"twins_tziah",
			"magus_tziah",
		},

		{
			"snake_tziah",
			"giant_tziah",
			"snake_tziah",
			"mother_tziah",
		},

		{
			"cyclops_tziah",
			"turret_tziah",
			"turret_tziah",
			"maya_tziah",
		},

		{
			"idol_tziah",
			"idol_tziah",
			"panzer_tziah",
		},

		{
			"gigas_tziah",
			"maya_tziah",
			"relic_tziah",
		},

		{
			"twins_tziah",
			"beast_tziah",
			"pesce_tziah",
		},

		{
			"machine_tziah",
			"mother_tziah",
		},
	},

	-- 55F:	Tziah boss 2: Intrepid Dancer
	[blockfloor[BLOCK_TZIAH] +10] = {
		{"dancer_boss1_tziah"},
	},

	-- 51F: Tziah random waves 2
	[blockfloor[BLOCK_TZIAH] +6] = {

		{
			"maya_tziah",
			"idol_tziah",
			"maya_tziah",
		},

		{
			"relic_tziah",
			"giant_tziah",
			"idol_tziah",
		},

		{
			"relic_tziah",
			"minotaur_tziah",
			"relic_tziah",
		},

		{
			"drive_tziah",
			"gigas_tziah",
			"gigas_tziah",
		},

		{
			"twins_tziah",
			"beetle_tziah",
			"twins_tziah",
		},

		{
			"maya_tziah",
			"minotaur_tziah",
			"snake_tziah",
		},

		{
			"snake_tziah",
			"giant_tziah",
			"snake_tziah",
		},

		{
			"cyclops_tziah",
			"turret_tziah",
			"turret_tziah",
		},

		{
			"idol_tziah",
			"idol_tziah",
		},

		{
			"gigas_tziah",
			"maya_tziah",
			"relic_tziah",
		},

		{
			"twins_tziah",
			"beast_tziah",
		},
	},

	-- 50F: Tziah boss 1: 3 Hell Knights
	[blockfloor[BLOCK_TZIAH]+5] = {
		{
			"knight_boss1_tziah",
			"knight_boss1_tziah",
			"knight_boss1_tziah"
		}
	},

	-- 45F: Tziah random waves 1
	[blockfloor[BLOCK_TZIAH]] = {

		{
			"maya_tziah",
			"maya_tziah",
			"maya_tziah",
		},

		{
			"relic_tziah",
			"giant_tziah",
			"relic_tziah",
		},

		{
			"relic_tziah",
			"minotaur_tziah",
			"relic_tziah",
		},

		{
			"drive_tziah",
			"gigas_tziah",
			"gigas_tziah",
		},

		{
			"twins_tziah",
			"beetle_tziah",
			"twins_tziah",
		},

		{
			"minotaur_tziah",
			"maya_tziah",
		},

		{
			"beast_tziah",
			"giant_tziah",
			"beast_tziah",
		},

		{
			"cyclops_tziah",
			"turret_tziah",
			"turret_tziah",
		},

		{
			"gigas_tziah",
			"maya_tziah",
			"relic_tziah",
		},

		{
			"twins_tziah",
			"beast_tziah",
		},
	},

	-- ENEMIES: YABBASHAH BLOCK
	-- 43F
	[blockfloor[BLOCK_YABBASHAH] +18] = {
		{
			"tower_boss1",
		},
	},

	-- 38F
	[blockfloor[BLOCK_YABBASHAH] +13] = {

		{
			"maya_3",
			"hand_2",
			"book_2",
			"maya_3",
		},

		{
			"sword_2",
			"beetle_2",
			"sword_2",
			"tiara_1",
		},

		{
			"book_2",
			"drive_1",
			"gene_1",

		},

		{
			"maya_3",
			"relic_2",
			"maya_3",
			"cupid_2",
		},

		{
			"tiara_2",
			"drive_1",
			"gene_1",
			"tiara_2",
		},

		{
			"mage_3",
			"relic_2",
			"mage_3",
			"hablerie_2",
		},

		{
			"maya_3",
			"mage_3",
			"tiara_2",
			"maya_3",
		},

		{
			"turret_1",
			"book_2",
			"hablerie_2",
		},

		{
			"sword_2",
			"turret_1",
			"sword_2",
			"gene_1",
		},

		{
			"hand_2",
			"tiara_2",
			"gene_1",
			"hand_2",
		},

		{
			"turret_1",
			"turret_1",
			"book_2",
		},

		{
			"knight_1",
			"tiara_2",
			"tiara_2",
		},
	},

	-- 37F
	[blockfloor[BLOCK_YABBASHAH] +12] = {
		{
			"magus_boss1",
			"magus_boss1",
			"magus_boss1",
		},
	},

	-- 31F
	[blockfloor[BLOCK_YABBASHAH] +6] = {

		{
			"maya_3",
			"hand_2",
			"book_2",
			"hablerie_2",
		},

		{
			"sword_2",
			"beetle_2",
			"sword_2",
			"tiara_1",
		},

		{
			"book_2",
			"hand_2",
			"book_2",

		},

		{
			"maya_3",
			"knight_1",
			"maya_3",
		},

		{
			"tiara_2",
			"drive_1",
			"tiara_2",
		},

		{
			"mage_3",
			"turret_1",
			"mage_3",
		},

		{
			"maya_3",
			"mage_3",
			"tiara_2",
			"maya_3",
		},

		{
			"turret_1",
			"book_2",
			"gene_1",
		},

		{
			"sword_2",
			"mage_3",
			"sword_2",
		},

		{
			"hand_2",
			"maya_3",
			"maya_3",
			"hablerie_2",
		},

		{
			"turret_1",
			"turret_1",
			"book_2",
		},

		{
			"knight_1",
			"tiara_2",
			"tiara_2",
		},
	},

	-- 30F
	[blockfloor[BLOCK_YABBASHAH] +5] = {
		{
			"gigas_boss1",
			"gigas_boss1",
			"gigas_boss1",
		},
	},

	[blockfloor[BLOCK_YABBASHAH]] = {

		{
			"maya_3",
			"maya_3",
			"book_2",
			"maya_3",
		},

		{
			"sword_2",
			"beetle_2",
			"sword_2",
		},

		{
			"book_2",
			"book_2",
			"book_2",

		},

		{
			"maya_3",
			"knight_1",
			"maya_3",
		},

		{
			"drive_1"
		},

		{
			"mage_3",
			"turret_1",
			"mage_3",
		},

		{
			"maya_3",
			"mage_3",
			"mage_3",
			"maya_3",
		},

		{
			"turret_1",
			"book_2",
		},

		{
			"sword_2",
			"mage_3",
			"sword_2",
		},

		{
			"maya_3",
			"maya_3",
			"maya_3",
			"maya_3",
		},

		{
			"turret_1",
			"turret_1",
			"book_2",
		},

		{
			"knight_1",
			"book_2",
			"book_2",
		},
	},
	-- ENEMIES: ARQA BLOCK

	[blockfloor[BLOCK_ARQA] +12] = {
		{	"relic_boss1"},
	},

	[blockfloor[BLOCK_ARQA] +6] = {

		{
			"book_1",
			"tiara_1_postboss",
			"beast_1_postboss",
			"basalt_1",
		},

		{	"wheel_1"},
		{	"wheel_1"},	-- make wave a bit more common		

		{
			"maya_2_postboss",
			"beast_1_postboss",
			"maya_2_postboss",
			"beast_1_postboss",
		},

		{
			"sword_1_postboss",
			"twins_1",
			"twins_1",
			"pesce_1_postboss",
		},

		{
			"tiara_1_postboss",
			"tiara_1_postboss",
			"basalt_1",
			"tiara_1_postboss",
		},

		{
			"balance_2",
			"balance_3",
			"fuzz_1_postboss",
		},

		{
			"balance_3",
			"maya_2_postboss",
			"maya_2_postboss",
		},

		{
			"twins_1",
			"book_1",
			"twins_1",
			"basalt_1",
		},
		
		{
			"pesce_1_postboss",
			"maya_2_postboss",
			"pesce_1_postboss",
		},
		
		{
			"fuzz_1_postboss",
			"basalt_1",
			"basalt_1",
			"fuzz_1_postboss",
		},
		
		{
			"balance_3",
			"pesce_1_postboss",
			"balance_3",
		},
		
		{
			"pesce_1_postboss",
			"twins_1",
			"twins_1",
			"fuzz_1_postboss",
		},
		
		{
			"basalt_1",
			"maya_2_postboss",
			"fuzz_1_postboss",
			"sword_1_postboss",
		},		

		{
			"sword_1_postboss",
			"maya_2_postboss",
			"pesce_1_postboss",
			"sword_1_postboss",
		},			
		
	},

	[blockfloor[BLOCK_ARQA] +5] = {
		{
			"beetle_boss1",
			"beetle_boss1",
			"beetle_boss1"
		}
	},

	[blockfloor[BLOCK_ARQA]] = {

		{
			"tiara_1",
			"tiara_1",
			"beast_1",
		},

		{	"wheel_1"},

		{
			"maya_2",
			"beast_1",
			"maya_2",
			"beast_1",
		},

		{
			"sword_1",
			"mage_2",
			"mage_2",
			"sword_1",
		},

		{
			"tiara_1",
			"tiara_1",
			"beetle_1",
			"tiara_1",
		},

		{
			"balance_2",
			"maya_2",
			"maya_2",
		},

		{
			"mage_2",
			"mage_2",
			"mage_2",
		},

		{
			"beetle_1",
			"beetle_1"
		},
		
		{
			"pesce_1",
			"maya_2",
			"pesce_1",
		},
		
		{
			"fuzz_1",
			"tiara_1",
			"tiara_1",
			"fuzz_1",
		},
		
		{
			"balance_2",
			"pesce_1",
			"balance_2",
		},
		
		{
			"pesce_1",
			"mage_2",
			"mage_2",
			"fuzz_1",
		},
		
		{
			"sword_1",
			"maya_2",
			"fuzz_1",
			"sword_1",
		},		

		{
			"sword_1",
			"maya_2",
			"pesce_1",
			"sword_1",
		},	
		
	},

	-- ENEMIES: THEBEL BLOCK
	[1] = {

		{	"maya_1",
			"maya_1",
			"maya_1",
		},
		
		{
			"hablerie_1",
			"hand_1",
		},
		
		{
			"maya_1",
			"hablerie_1",
			"maya_1",
		},

		{	"hand_1",
			"hand_1",
		},

		{	"table_1",
			"table_1",
			"maya_1",
		},

		{	"table_1",
			"maya_1",
			"hand_1"
		},
		
		{
			"table_1",
			"hablerie_1",
			"hand_1",
		},	
		
		{
			"balance_1",
			"hablerie_1",
			"maya_1",
		},

		{	"balance_1",
			"balance_1"},

		{	"beetle_1"},	
		{	"beetle_1"},	-- make this wave slightly more common lol
	},

	[5] = {
		{
			"table_boss1",
			"table_boss1",
			"table_boss1",
		},
	},

	[6] = {

		{	"balance_1_postboss",
			"table_1_postboss",
			"balance_1_postboss"
		},

		{	"hablerie_1_postboss",
			"beetle_1",
			"maya_1_postboss"
		},

		{	"table_1_postboss",
			"mage_1",
			"table_1_postboss"
		},

		{	"relic_1",
			"maya_1_postboss",
			"cupid_1",
		},

		{	"hand_1_postboss",
			"relic_1",
			"hand_1_postboss",
		},

		{	"maya_1_postboss",
			"cupid_1",
			"maya_1_postboss",
			"maya_1_postboss"
		},

		{	"maya_1_postboss",
			"balance_1_postboss",
			"maya_1_postboss",
			"balance_1_postboss"
		},

		{	"table_1_postboss",
			"table_1_postboss",
			"table_1_postboss"
		},
		
		{
			"hablerie_1_postboss",
			"cupid_1",
			"hablerie_1_postboss",
		},
		
		{
			"table_1_postboss",
			"cupid_1",
			"cupid_1",
			"hablerie_1_postboss",
		},

	},

	[9] = {
		{	"drive_boss1"
		}
	},

})

local errored = 0
for k, v in pairs(DNG_waves)
	
	if v 
		
		for i = 1, #v do
			if v[i]
				
				for j = 1, #v[i] do
					
					if not enemyList[v[i][j]]
						print("Floor "..k..", wave "..i..", Enemy "..v[i][j].." does not exist.")
						errored = $+1
					end
				end
			end
		end
	end
end

print("Enemy wave data loaded with "..errored.." errors")