-- personas for tartarus
-- separated in floors

rawset(_G, "DNG_subpersonas", {
[2] = 	{
		"jack frost",
		"angel",
		"nata taishi",
		"pixie",
		"ghoul"
		},

[blockfloor[BLOCK_ARQA]] = {
		"pyro jack",
		"principality",
		"naga",
		"lamia",
		"fortuna",
		"narcissus",
		"oberon",
		},

[blockfloor[BLOCK_YABBASHAH]] = {
		"hua po",
		"orobas",
		"leanan sidhe",
		"king frost",
		"queen mab",
		"ares",
		"mithra",
		"lilim",
		},

[blockfloor[BLOCK_TZIAH]] = {
		"black frost",
		"chu chulainn",
		"girimehkala",
		"kaiwan",
		"oumitsunu",
		"pale rider",
		"succubus",
		"titania",
		"virtue",
		},

[blockfloor[BLOCK_HARABAH]] = {
		"anubis",
		"kinki",
		"quezacoatl",
		"belphegor",
		"siegfried",
		"matador",
		"hell biker",
		"byakko",
		"seiryuu",
		"mara",
},

[blockfloor[BLOCK_ADAMAH]] = {
		"trumpeter",
		"lilith",
		"archangel",
		"raphael",
		"sati",
		"loki",
		"alice",
		"daisoujou",
		},

})